env:
  - GHCVER=7.10.1
  - GHCVER=7.8.4

before_install:
  - sudo add-apt-repository -y ppa:hvr/ghc
  - sudo apt-get update
  - sudo apt-get install cabal-install-1.22 ghc-$GHCVER
  - export PATH=/opt/ghc/$GHCVER/bin:$PATH
  - sudo apt-get install happy-1.19.4 alex-3.1.3
  - export PATH=/opt/alex/3.1.3/bin:/opt/happy/1.19.4/bin:$PATH

install:
  - cabal-1.22 update
  - cabal-1.22 install -j --only-dep  --enable-tests --force-reinstalls

script:
  - cabal-1.22 configure --enable-tests --enable-library-coverage && cabal-1.22 build && cabal-1.22 test

after_script:
  - cabal-1.22 install hpc-coveralls --bindir=$HOME/.cabal/bin/
  - $HOME/.cabal/bin/hpc-coveralls --exclude-dir=test test-memcache
